baseURL = 'http://yasd.fans/'
languageCode = 'zh-cn'
title = 'YASD-Roguelike fans CN'
theme = "yasdstyle"

[menu]
  [[menu.main]]
    name = "主页"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "关于"
    pre = "about"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "文章"
    pre = "文章"
    url = "/posts/"
    weight = 3
[params]
    ascii_art ='''put your ascii art title here.'''

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true